version: 0.2
phases:
  install:
    commands:
      - echo Entered the install phase...
      - apt-get update -y
	  
  pre_build:
    commands:
      - echo Entered the pre_build phase...
	  
  build:
    commands:
      - echo "This is build phase...Zipping my webpage"

  post_build:
    commands:
      - echo "Deployed to S3"

artifacts:
  files:
    - '**/*'
